import Link from "next/link";
import { ArrowLeft, Lightbulb, DollarSign, Leaf, ArrowRight } from "lucide-react";

export default function LosAngelesCaseStudy() {
  return (
    <div className="container mx-auto px-4 sm:px-6 lg:px-8 py-20">
      <Link
        href="/case-studies"
        className="text-primary font-semibold hover:underline inline-flex items-center mb-8"
      >
        <ArrowLeft className="mr-2 w-4 h-4" /> Back to Case Studies
      </Link>

      <h1 className="text-4xl md:text-5xl font-serif font-bold text-foreground mb-6">
        Los Angeles: Leading the LED Revolution
      </h1>
      <p className="text-xl text-muted-foreground mb-12 max-w-3xl">
        How the City of Angels became a shining example of energy efficiency and
        smart city innovation.
      </p>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-8 mb-12">
        <FactCard
          icon={<Lightbulb className="w-12 h-12 text-primary" />}
          title="140,000+"
          description="Street lights converted to LED"
        />
        <FactCard
          icon={<DollarSign className="w-12 h-12 text-primary" />}
          title="$9 Million"
          description="Annual savings in energy costs"
        />
        <FactCard
          icon={<Leaf className="w-12 h-12 text-primary" />}
          title="60%"
          description="Reduction in energy consumption"
        />
      </div>

      <div className="prose max-w-none mb-12">
        <h2>Project Overview</h2>
        <p>
          In 2013, Los Angeles completed the world&apos;s largest LED street light
          retrofit project, converting over 140,000 sodium vapor street lights
          to LED over a period of seven years. This massive undertaking not only
          improved the quality of lighting across the city but also resulted in
          significant energy and cost savings.
        </p>

        <h2>Innovative Approach</h2>
        <p>
          What sets Los Angeles apart is their innovative approach to utilizing
          the savings generated by the LED conversion. The city has reinvested
          both the financial savings and the excess power capacity into
          converting their LED street lamps into electric vehicle charging
          stations, further enhancing their green initiatives.
        </p>

        <h2>Results and Benefits</h2>
        <ul>
          <li>Annual savings of $9 million in energy costs</li>
          <li>Reduction in energy consumption by approximately 60%</li>
          <li>Improved visibility and safety for pedestrians and drivers</li>
          <li>Decreased light pollution and sky glow</li>
          <li>Reduced maintenance costs due to longer-lasting LED bulbs</li>
          <li>Creation of a network of electric vehicle charging stations</li>
        </ul>

        <h2>Lessons Learned</h2>
        <p>
          Los Angeles&apos; success demonstrates the potential for large-scale LED
          street light conversions to not only save money and reduce energy
          consumption but also to serve as a foundation for further smart city
          initiatives. The project&apos;s success has inspired many other cities to
          follow suit, making it a true leader in urban sustainability.
        </p>
      </div>

      <div className="bg-muted rounded-lg p-8 mb-12">
        <h2 className="text-2xl font-serif font-bold text-foreground mb-4">
          How Bright America Bonds Can Help
        </h2>
        <p className="text-muted-foreground mb-4">
          Bright America Bonds can provide the financing needed for cities to
          implement large-scale LED street light conversion projects like Los
          Angeles&apos;. Our innovative funding model allows cities to modernize
          their infrastructure without upfront costs, using the energy savings
          to repay the bonds over time.
        </p>
        <Link
          href="/for-cities"
          className="text-primary font-semibold hover:underline inline-flex items-center"
        >
          Learn More About Our Solutions for Cities{" "}
          <ArrowRight className="ml-2 w-4 h-4" />
        </Link>
      </div>

      <div className="text-center">
        <h2 className="text-3xl font-serif font-bold text-foreground mb-6">
          Ready to Light Up Your City&apos;s Future?
        </h2>
        <Link href="/contact" className="btn-primary">
          Contact Us to Get Started
        </Link>
      </div>
    </div>
  );
}

const FactCard = ({
  icon,
  title,
  description,
}: {
  icon: React.ReactNode;
  title: string;
  description: string;
}) => (
  <div className="bg-background p-6 rounded-lg shadow-md border border-border text-center">
    <div className="mb-4 flex justify-center">{icon}</div>
    <h3 className="text-2xl font-bold mb-2 text-foreground">{title}</h3>
    <p className="text-muted-foreground">{description}</p>
  </div>
);
